{
    "affected": [
        {
            "package": {
                "ecosystem": "Debian:8",
                "name": "python-django",
                "purl": "pkg:deb/debian/python-django?distro=jessie&repository_url=http%3A%2F%2Fdeb.freexian.com%2Fextended-lts"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "1.7.11-1+deb8u17"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        },
        {
            "package": {
                "ecosystem": "Debian:9",
                "name": "python-django",
                "purl": "pkg:deb/debian/python-django?distro=stretch&repository_url=http%3A%2F%2Fdeb.freexian.com%2Fextended-lts"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "1:1.10.7-2+deb9u23"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        }
    ],
    "database_specific": {
        "type": "security update"
    },
    "id": "ELA-1163-1",
    "modified": "2024-08-27T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://deb.freexian.com/extended-lts/tracker/ELA-1163-1"
        },
        {
            "type": "ADVISORY",
            "url": "https://deb.freexian.com/extended-lts/tracker/CVE-2024-41989"
        }
    ],
    "related": [
        "CVE-2024-41989"
    ]
}